# Generated by Django 3.2.5 on 2021-07-16 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=20)),
                ('destination', models.CharField(max_length=20)),
                ('is_available', models.BooleanField(default=True)),
                ('available_seat', models.IntegerField()),
                ('ticket_price', models.IntegerField()),
                ('trip_number', models.IntegerField()),
                ('trip_date', models.DateField()),
                ('trip_time', models.DateTimeField()),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminn.train')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tickets_price', models.IntegerField()),
                ('seat_number', models.IntegerField()),
                ('train_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminn.train')),
                ('trip_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.trip')),
            ],
        ),
    ]
